[project]
name = "top-coder-challenge-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gplearn>=0.4.2",
    "numpy>=2.3.0",
    "scikit-learn>=1.7.0",
    "xgboost>=2.1.0",
    "pandas>=2.2.0",
]
